### PR TITLE
Added connection DB flag to tsbs_load_timescaledb

### PR DESCRIPTION
**Pull request by antekresic**

### CODE REVIEW

**Comment by RobAtticus** [comment]
This functionality is already exposed via the `--db-name` flag, no?:
```
$ tsbs_load_timescaledb --help
Usage of tsbs_load_timescaledb:
...
  -db-name string
    	Name of database (default "benchmark")
...
```

(The flag is defined/exists in the `load` pkg since it is shared across loaders)

**Comment by RobAtticus** [comment]
Ah I think this is supposed to solve a different problem -- connecting when you want to create the original database? May need to work on some naming issues here.

**Comment by antekresic** [comment]
Yeah, this is regarding issue #39. I thought that as well at first but I guess people need something like this when connecting to the database where they have to use a custom database name. 

How about `--custom-conn-db`? Or should we change the other flag name to make it more distinct from this one?

**Comment by RobAtticus** [comment]
Let's go with `--admin-db-name` and a description like:
```
Database to connect to in order to create additional benchmark databases. By default this is the same as the `db-user` (i.e., `postgres` if neither is set), but sometimes a user does not have its own database.
```
A bit of a mouthful, but gets it across. Then maybe update the commit message to give an extended explaining the reason/need for this change.

Appreciate the PR!

**Comment by antekresic** [comment]
Updated PR based on the recent comment.

Let me know if there is anything else that needs changing.

Thanks!

**Comment by RobAtticus** [comment]
Hi @antekresic, I think you need to rebase your branch on the latest (rather than merge ours into yours) because now there are some duplicated commits in your PR. And then squash all your commits into one.

**Comment by antekresic** [comment]
Hey @RobAtticus 

Sorry about that, I took a wrong turn rebasing the branch previously. I believe its fixed now.

**Pull request merged**
